<?php
// @codingStandardsIgnoreFile
?>
<?php
$_helper = $this->helper('WeltPixel\GA4\Helper\Data');
?>
<?php if ($_helper->isEnabled()) : ?>
    <script data-breeze>
        require(['jquery','weltpixel_ga4_persistentLayer','weltpixel_ga4_gtm', 'Magento_Customer/js/customer-data'],
            function ($, wpGa4PersDl ,wpGa4gtm, customerData) {
                $(document).off('ajaxComplete.weltpixel_ga4');
                $(document).on('ajaxComplete.weltpixel_ga4', function (event, data) {
                    if (data.response.url.search('/customer\/section\/load/') > 0) {
                        var response = data.response.body;
                        if (response.wp_ga4) {
                            var dataLayerData = JSON.parse(response.wp_ga4.datalayer);
                            for (index in dataLayerData) {
                                window.dataLayer.push({ecommerce: null});
                                window.dataLayer.push(dataLayerData[index]);
                            }
                        }
                    }
                });
                var wpPersDlOptions = {'storageExpiryTime' : <?php echo $_helper->getPersistentStorageExpiryTime() ?> };
                var wpGtmOptions = {
                    'enabled' : <?php echo $_helper->trackPromotions() ?>,
                    'persDataLayer' : wpGa4PersDl
                };
                wpGa4PersDl.init(wpPersDlOptions);
                wpGa4gtm.trackPromotion(wpGtmOptions);
            });
    </script>
<?php endif; ?>
